create table customers (
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	gender VARCHAR(7) NOT NULL,
	country VARCHAR(50) NOT NULL,
	Credit_Card VARCHAR(50) NOT NULL
);
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Collette', 'Trematick', 'Female', 'Indonesia', 'switch');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Edyth', 'Kilgallon', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Vittorio', 'McKinnon', 'Male', 'Indonesia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Ericka', 'Treleven', 'Female', 'Brazil', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Carlyle', 'Hilbourne', 'Male', 'France', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Heath', 'Damp', 'Male', 'Indonesia', 'visa-electron');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Courtenay', 'Street', 'Female', 'United Kingdom', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Inglebert', 'Vince', 'Male', 'China', 'bankcard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Noreen', 'Benz', 'Female', 'Cuba', 'visa');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Sly', 'Golden', 'Male', 'Morocco', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Marlon', 'Affleck', 'Male', 'Moldova', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Paolo', 'Nodin', 'Male', 'Tunisia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Hermann', 'Duprey', 'Male', 'Swaziland', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Siegfried', 'Lamb', 'Male', 'China', 'maestro');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Jackson', 'Castellani', 'Male', 'China', 'switch');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Fairlie', 'Lanfer', 'Male', 'Ukraine', 'maestro');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Derron', 'Wabersinke', 'Male', 'Zambia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Broderick', 'Corfield', 'Male', 'United States', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Yorker', 'Castangia', 'Male', 'Japan', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Mahmoud', 'Tuplin', 'Male', 'Belarus', 'americanexpress');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Agnola', 'Fanton', 'Female', 'Indonesia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Ula', 'Rappaport', 'Female', 'Colombia', 'diners-club-enroute');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Danny', 'Scay', 'Male', 'Czech Republic', 'china-unionpay');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Worthy', 'Reinbeck', 'Male', 'Portugal', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Guenevere', 'Mobbs', 'Female', 'Canada', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Jonie', 'Jeffes', 'Female', 'Denmark', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Jesus', 'Burling', 'Male', 'Myanmar', 'diners-club-carte-blanche');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Asa', 'Whillock', 'Male', 'China', 'china-unionpay');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Red', 'Croke', 'Male', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Wyndham', 'Hutchins', 'Male', 'Indonesia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Norene', 'Wildgoose', 'Female', 'Brazil', 'americanexpress');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Haleigh', 'Peer', 'Female', 'Greece', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Goldia', 'Kyle', 'Female', 'Indonesia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Franz', 'Izakovitz', 'Male', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Wallis', 'Grunnell', 'Female', 'Poland', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Glenn', 'Satterlee', 'Male', 'Indonesia', 'switch');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Perri', 'Russo', 'Female', 'Guatemala', 'visa-electron');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Bliss', 'Von Der Empten', 'Female', 'Uzbekistan', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Shell', 'Guiduzzi', 'Male', 'Russia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Nestor', 'Thirlwell', 'Male', 'Poland', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Alix', 'Machan', 'Female', 'Peru', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Valeria', 'Forshaw', 'Female', 'Peru', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Elwood', 'Burnand', 'Male', 'Philippines', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Isidora', 'Nitto', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Morna', 'MacCaffrey', 'Female', 'Indonesia', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Fran', 'Blissitt', 'Male', 'China', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Rebeka', 'Bilverstone', 'Female', 'Thailand', 'laser');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Dennet', 'Davenell', 'Male', 'Indonesia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Leigha', 'Rawlyns', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Alleen', 'Jope', 'Female', 'Netherlands', 'visa-electron');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Willem', 'Bacup', 'Male', 'Argentina', 'visa-electron');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Ruthie', 'Kleinzweig', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Celie', 'Gainsburgh', 'Female', 'Iran', 'laser');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Salomone', 'Lombard', 'Male', 'China', 'americanexpress');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Berri', 'Raect', 'Female', 'Indonesia', 'switch');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Vivienne', 'Wycliffe', 'Female', 'Uruguay', 'maestro');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Federica', 'Culpan', 'Female', 'Indonesia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Desiri', 'Jauncey', 'Female', 'Slovenia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Emmery', 'Eddisford', 'Male', 'Chile', 'switch');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Conroy', 'Trees', 'Male', 'Mongolia', 'solo');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Shell', 'Quimby', 'Female', 'Russia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Gar', 'Meach', 'Male', 'China', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Kylie', 'Hakes', 'Female', 'Russia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Sutherlan', 'Kobke', 'Male', 'United States', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Carlo', 'Males', 'Male', 'Russia', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Roberto', 'Ebbins', 'Male', 'Brazil', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Odelinda', 'Cotta', 'Female', 'Colombia', 'diners-club-carte-blanche');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Christin', 'Jarritt', 'Female', 'Mauritius', 'diners-club-carte-blanche');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Odie', 'De Maria', 'Male', 'Laos', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Dotty', 'Bosma', 'Female', 'China', 'maestro');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Beatriz', 'Goldthorp', 'Female', 'United States', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Fletch', 'Getcliff', 'Male', 'Uzbekistan', 'americanexpress');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Odella', 'Creffeild', 'Female', 'Ukraine', 'americanexpress');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Bianka', 'McMichell', 'Female', 'Bolivia', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Fidole', 'Lebrun', 'Male', 'South Africa', 'mastercard');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Berkly', 'Nowick', 'Male', 'Syria', 'maestro');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Dalis', 'Coward', 'Male', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Millard', 'Barhams', 'Male', 'China', 'americanexpress');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Paton', 'Bierton', 'Male', 'Malta', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Minnie', 'Chessell', 'Female', 'Russia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Morly', 'Melloy', 'Male', 'Sweden', 'americanexpress');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Whitby', 'Irvine', 'Male', 'China', 'china-unionpay');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Davin', 'MacDougall', 'Male', 'Iceland', 'switch');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Idalina', 'Guttridge', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Hana', 'Penhaleurack', 'Female', 'Philippines', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Ammamaria', 'Woodham', 'Female', 'Peru', 'diners-club-enroute');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Matthaeus', 'Whates', 'Male', 'China', 'visa');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Corliss', 'Beamand', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Regan', 'Pippin', 'Male', 'Indonesia', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Sonnie', 'Gasquoine', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Quincey', 'Klewer', 'Male', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Gilbertina', 'Imesen', 'Female', 'Palestinian Territory', 'diners-club-enroute');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Cthrine', 'Kellick', 'Female', 'Iran', 'china-unionpay');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Dyana', 'Schulze', 'Female', 'Portugal', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Irena', 'Bage', 'Female', 'Portugal', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Peta', 'Harriagn', 'Female', 'Ukraine', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Karita', 'Oloman', 'Female', 'China', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Hasheem', 'Hydes', 'Male', 'Thailand', 'laser');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Colline', 'Werlock', 'Female', 'Greece', 'jcb');
insert into customers (first_name, last_name, gender, country,  Credit_Card) values ('Tedd', 'Tarpey', 'Male', 'Poland', 'laser');
